### ISSUE TITLE
Any difference from using the images in https://sourceforge.net/projects/waydroid/ ?

### ISSUE THREAD

**Issue by VarLad** [aleasto/waydroid-ota#1]
Can I use the images from there, when using the COPR? 
If not, is it possible to set up a CI to update your images more regularly, since last update seems to be a month ago, while waydroid images update frequently?

**Comment by aleasto** [comment]
The previous update was 3 months ago so I had to build my own images to support ashmem-less linux.

I see there's a new update today which means you can use the official images. However the built-in browser or any application that uses a WebView will crash, as that will require chromium version 101 while my images have backported the patch.

You can switch over with `sudo waydroid init -f -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor`

**Comment by aleasto** [comment]
I'm sorry i don't know what you mean. As I said my images already contain a working version of chromium WebView.

**Comment by VarLad** [comment]
Ah sorry, I thought the ones on Waydroid would be "more updated"

I guess both images are the same, except, yours have the Chromium backport

**Comment by VarLad** [comment]
@aleasto Hey! 
I'm reinstalling waydroid right now. 
Unfortunately, the download speed is too low when I try downloading the images via `sudo waydroid init -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor` but when I fetch the image directly from `https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-17.1-20220316-VANILLA-waydroid_x86_64-system.zip/download`, it seems to be super fast. 

Can I somehow use a local image when trying to init waydroid downloaded with your COPR? Also I'm aware there's one more file which needs to be downloaded! If possible, can you point me to that as well? Thank you
